version: '3.7'

services:

  stratton-ashwood-test:
    tty: true
    container_name: stratton-ashwood-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true